#!/bin/bash

#Check if helm command is installed
type helm > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "This script requires the helm command. Please install helm to proceed further"
    exit 1
fi

TMPL_FILE=detemplatized_manifests.yaml
for VERS in `ls -1 deploy/kubernetes/ | grep -v latest`
do
    helm template cte-tmpl deploy/kubernetes/${VERS} > ${TMPL_FILE}
    if [ $? -ne 0 ]; then
        echo "Error encountered running the 'helm template' command"
        exit 1
    fi

    # Everything is returned in one big file, split the files into individual manifests
    j=$(grep -c -- "---" ${TMPL_FILE})    # Number of manifests in the generated yaml file
    k=$((${j}-1))                         # Number of splits to perform
    csplit -f cte-csi-csplit_ ${TMPL_FILE} /---/ {${k}} > /dev/null

    # The first file in our case is always empty as the TMPL_FILE starts with ---, discard it
    rm cte-csi-csplit_00

    #rename each of the manifest file to match the existing names in the cte-k8s-operator repo
    for i in $(ls ./cte-csi-csplit_*)
    do
        NAME=$(awk '/Source/ { printf $NF }' $i | xargs basename | sed -e s/rbac-//g)
        KIND=$(awk '/^kind:/ { printf $NF }' $i)

        case ${KIND} in
            ServiceAccount)
                KIND=sa
                # rename xyz.yaml as xyz-sa.yaml
                NAME=$(echo ${NAME} | sed -e s/.yaml/\-${KIND}.yaml/g)
                sed -i '/^  namespace: .*/d' $i
                ;;
            ClusterRole)
                KIND=role
                # rename xyz.yaml as xyz-role.yaml
                NAME=$(echo ${NAME} | sed -e s/.yaml/\-${KIND}.yaml/g)
                ;;
            ClusterRoleBinding)
                KIND=role-binding
                # rename xyz.yaml as xyz-role-binding.yaml
                NAME=$(echo ${NAME} | sed -e s/.yaml/\-${KIND}.yaml/g)
                ;;
            CSIDriver)
                NAME=cte-csi-csidriver.yaml
                ;;
            ConfigMap)
                NAME=cte-k8s-config.yaml
        esac

        # Remove unwanted lines from the file
        sed -i '/^---/d' $i
        sed -i '/^# Source: /d' $i

        mkdir -p custom_manifests/${VERS}
        # Move the generated and renamed manifests to the appropriate staging dir for packaging
        case ${KIND} in
            sa|role|role-binding)
                # To be implemented on future release
                ;;
            *)
                mv ${i} custom_manifests/${VERS}/${NAME}
                ;;
        esac
    done

    # Remove files generated by csplit and the detemplatized manifest file generated earlier
    rm -f cte-csi-csplit_* ${TMPL_FILE}
done
